name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C environment for linting
      uses: cpp-linter/cpp-linter-action@v2

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Build
      run: make

    - name: Run cppcheck lint
      run: make lint
